# Generated by Django 5.2.12 on 2026-03-31 13:20

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_tenant_branding_storage_charfields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "applicable_vehicle_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Vehicle type codes this category applies to (e.g. ['car','motorcycle']). Empty = all types.",
                        size=None,
                    ),
                ),
                ("icon_code", models.CharField(blank=True, max_length=50, null=True)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "service categories",
                "db_table": "service_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hsn_code", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("per_service", "Per Service"),
                            ("per_hour", "Per Hour"),
                            ("per_km", "Per KM"),
                        ],
                        default="per_service",
                        max_length=20,
                    ),
                ),
                (
                    "applicable_vehicle_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Overrides category filter. Empty = inherits from category.",
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="services.servicecategory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_items",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_items",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["tenant", "name"], name="service_cat_tenant__6ab6e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["tenant", "is_active"], name="service_cat_tenant__f35ff6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                condition=models.Q(("is_archived", False)),
                name="uniq_service_category_name_per_tenant_active",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceitem",
            index=models.Index(
                fields=["tenant", "category"], name="service_ite_tenant__2ae53c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceitem",
            index=models.Index(
                fields=["tenant", "is_active"], name="service_ite_tenant__625def_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceitem",
            constraint=models.UniqueConstraint(
                models.F("category"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("is_archived", False)),
                name="uniq_service_item_name_per_category_active",
            ),
        ),
    ]
