# Generated by Django 5.2.12 on 2026-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_serviceitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceitem",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Relative storage key (LOCAL path or S3 key) for the service item icon/image.",
                max_length=512,
                null=True,
            ),
        ),
    ]
