# Generated by Django 5.2.12 on 2026-08-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_serviceitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="service_type",
            field=models.CharField(
                choices=[("part", "Part"), ("labour", "Labour")],
                default="labour",
                max_length=10,
            ),
        ),
    ]
