# Generated by Django 5.2.12 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_serviceitem_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive of GST"),
                    ("inclusive", "Inclusive of GST"),
                ],
                default="exclusive",
                help_text="Whether base_price already includes GST ('inclusive', e.g. a fixed ₹1200 package rate) or GST is added on top of it ('exclusive', the default — matches all pre-existing service items).",
                max_length=10,
            ),
        ),
    ]
