# Generated by Django 5.2.12 on 2026-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_serviceitem_price_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
