# Generated by Django 5.2.12 on 2026-04-01 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_move_state_city_to_masters"),
        ("tenants", "0004_tenant_branding_storage_charfields"),
        ("vehicles", "0008_add_vehicle_type_to_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jobcard_number", models.CharField(db_index=True, max_length=32)),
                ("services_items", models.JSONField(blank=True, default=list)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In progress"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("invoiced", "Invoiced"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("km_reading", models.PositiveIntegerField(blank=True, null=True)),
                ("next_service_km", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_job_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_cards",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_cards",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_cards",
                        to="vehicles.servicevehicle",
                    ),
                ),
            ],
            options={
                "db_table": "job_cards",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="job_cards_tenant__77eaa9_idx"
                    ),
                    models.Index(
                        fields=["tenant", "customer"],
                        name="job_cards_tenant__0b28af_idx",
                    ),
                    models.Index(
                        fields=["tenant", "vehicle"],
                        name="job_cards_tenant__09c129_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "jobcard_number"),
                        name="uniq_jobcard_number_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JobCardFySequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fy_code", models.CharField(db_index=True, max_length=5)),
                ("last_seq", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_card_fy_sequences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "job_card_fy_sequences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "fy_code"),
                        name="uniq_jobcard_fy_seq_per_tenant",
                    )
                ],
            },
        ),
    ]
