# Generated by Django 5.2.12 on 2026-04-01 13:25

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def forwards_migrate_json_lines(apps, schema_editor):
    JobCard = apps.get_model("jobcards", "JobCard")
    JobCardLineItem = apps.get_model("jobcards", "JobCardLineItem")
    ServiceItem = apps.get_model("services", "ServiceItem")

    for jc in JobCard.objects.all():
        raw = getattr(jc, "services_items", None)
        if not raw or not isinstance(raw, list):
            continue
        for idx, line in enumerate(raw):
            if not isinstance(line, dict):
                continue
            qty = Decimal(str(line.get("qty") or line.get("quantity") or 1))
            up = Decimal(str(line.get("base_price") or line.get("unit_price") or 0))
            da = Decimal(str(line.get("discount_amount") or line.get("line_discount") or 0))
            if da < 0:
                da = Decimal("0")
            lt_raw = line.get("line_total")
            if lt_raw is not None:
                lt = Decimal(str(lt_raw)).quantize(Decimal("0.01"))
            else:
                net = qty * up - da
                lt = (net if net > 0 else Decimal("0")).quantize(Decimal("0.01"))
            desc = line.get("name") or line.get("description") or "Service line"
            sid = line.get("service_id")
            fk = None
            if sid:
                try:
                    si = ServiceItem.objects.get(pk=sid, tenant_id=jc.tenant_id)
                    fk = si.pk
                except Exception:
                    fk = None
            JobCardLineItem.objects.create(
                job_card_id=jc.pk,
                sort_order=int(line.get("sort_order", idx)),
                service_item_id=fk,
                description=str(desc)[:500],
                quantity=qty,
                unit_price=up,
                discount_amount=da,
                line_total=lt,
            )


def backwards_clear_lines(apps, schema_editor):
    JobCardLineItem = apps.get_model("jobcards", "JobCardLineItem")
    JobCardLineItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCardLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="jobcards.jobcard",
                    ),
                ),
                (
                    "service_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_card_lines",
                        to="services.serviceitem",
                    ),
                ),
            ],
            options={
                "db_table": "job_card_line_items",
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_card", "sort_order"],
                        name="job_card_li_job_car_449aae_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(forwards_migrate_json_lines, backwards_clear_lines),
        migrations.RemoveField(
            model_name="jobcard",
            name="services_items",
        ),
    ]
