# Generated by Django 5.2.12 on 2026-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0002_job_card_line_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="shop_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Non-GST shop / handling fee added after tax on the job card.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="jobcardlineitem",
            name="detail_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional secondary line (e.g. catalog detail); avoid unnecessary PII.",
                max_length=500,
            ),
        ),
    ]
