# Generated by Django 5.2.12 on 2026-04-07 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_add_photo_to_customer"),
        ("jobcards", "0003_shop_fees_and_line_detail"),
        ("tenants", "0004_tenant_branding_storage_charfields"),
        ("vehicles", "0009_add_photo_to_service_vehicle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobcard",
            options={"ordering": ["-created_at", "-jobcard_number"]},
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                fields=["tenant", "created_at"], name="job_cards_tenant__2ea970_idx"
            ),
        ),
    ]
