# Generated by Django 5.2.12 on 2026-04-08 17:06

from django.db import migrations, models


# Old → new status slug mapping. draft + confirmed collapse into job_control;
# in_progress → working; on_hold → ready_for_fi; the rest keep their slugs.
_FORWARD_MAP = {
    "draft": "job_control",
    "confirmed": "job_control",
    "in_progress": "working",
    "on_hold": "ready_for_fi",
}

# Reverse migration is lossy: job_control rows previously came from either
# draft or confirmed — we map them all back to draft as a safe default.
_REVERSE_MAP = {
    "job_control": "draft",
    "working": "in_progress",
    "ready_for_fi": "on_hold",
}


def _remap(apps, schema_editor, mapping):
    JobCard = apps.get_model("jobcards", "JobCard")
    for old, new in mapping.items():
        JobCard.objects.filter(status=old).update(status=new)


def forwards(apps, schema_editor):
    _remap(apps, schema_editor, _FORWARD_MAP)


def backwards(apps, schema_editor):
    _remap(apps, schema_editor, _REVERSE_MAP)


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0004_jobcard_tenant_created_at_index"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="jobcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("job_control", "Job Control"),
                    ("working", "Working"),
                    ("ready_for_fi", "Ready for FI"),
                    ("completed", "Job Completed"),
                    ("invoiced", "Invoice"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="job_control",
                max_length=20,
            ),
        ),
    ]
