# Generated by Django 5.2.12 on 2026-08-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0006_add_next_service_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcardlineitem",
            name="service_type",
            field=models.CharField(
                choices=[("part", "Part"), ("labour", "Labour")],
                default="labour",
                max_length=10,
            ),
        ),
    ]
