# Generated by Django 5.2.12 on 2026-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0007_jobcardlineitem_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcardlineitem",
            name="cgst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="jobcardlineitem",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Snapshot of the linked catalog service item's GST% at sync time (0 for custom lines).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="jobcardlineitem",
            name="sgst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
