# Generated by Django 4.2.29 on 2026-08-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0008_jobcardlineitem_cgst_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="pdf_key",
            field=models.CharField(
                blank=True,
                help_text="Relative path (LOCAL) or S3 object key for the generated job card PDF.",
                max_length=512,
                null=True,
            ),
        ),
    ]
