# Generated by Django 5.2.12 on 2026-09-06 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0010_jobcard_round_off_amount"),
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this job card was created from an approved quotation. Optional — direct job card creation is unaffected.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_cards",
                to="quotations.quotation",
            ),
        ),
    ]
