# Generated by Django 5.2.12 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcards", "0011_jobcard_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcardlineitem",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive of GST"),
                    ("inclusive", "Inclusive of GST"),
                ],
                default="exclusive",
                help_text="Snapshot of the linked catalog service item's price_type at sync time (always 'exclusive' for custom lines with no catalog match). When 'inclusive', unit_price is GST-inclusive and line_total holds the reverse-calculated taxable value, not unit_price*quantity.",
                max_length=10,
            ),
        ),
    ]
