# Generated by Django 5.2.12 on 2026-03-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_consent_consenttype_remove_user_last_consent_at_and_more"),
    ]

    operations = []
