# Generated by Django 5.2.12 on 2026-03-20 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("users", "0003_remove_consent_consent_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFCMToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fcm_token", models.TextField(db_index=True, unique=True)),
                (
                    "device_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[("platform", "Platform"), ("portal", "Portal")],
                        db_index=True,
                        default="portal",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_fcm_tokens",
                "indexes": [
                    models.Index(
                        fields=["user", "device_id", "app"],
                        name="fcm_user_device_app_idx",
                    ),
                    models.Index(fields=["tenant", "user"], name="fcm_tenant_user_idx"),
                    models.Index(
                        fields=["is_active", "last_used_at"], name="fcm_active_used_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("device_id__isnull", False)),
                        fields=("user", "device_id", "app"),
                        name="fcm_unique_user_device_app",
                    )
                ],
            },
        ),
    ]
