# Generated by Django 5.2.12 on 2026-03-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_onboarded_at"),
        ("users", "0004_userfcmtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="tenants.tenant",
            ),
        ),
    ]
