# Generated by Django 4.2.29 on 2026-03-27 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0004_tenant_branding_storage_charfields"),
        ("customers", "0003_move_state_city_to_masters"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "vehicle_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("registration_no", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("year", models.SmallIntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("ev", "EV"),
                            ("cng", "CNG"),
                            ("hybrid", "Hybrid"),
                            ("lpg", "LPG"),
                            ("electric_hybrid", "Electric-Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("engine_cc", models.SmallIntegerField(blank=True, null=True)),
                (
                    "battery_capacity_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("vin_number", models.CharField(blank=True, max_length=17, null=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("puc_expiry", models.DateField(blank=True, null=True)),
                ("permit_expiry", models.DateField(blank=True, null=True)),
                ("fitness_cert_expiry", models.DateField(blank=True, null=True)),
                ("no_of_wheels", models.SmallIntegerField(blank=True, null=True)),
                ("load_capacity_kg", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_vehicles",
                        to="customers.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_vehicles",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_vehicles",
                        to="vehicles.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "service_vehicles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "customer"],
                        name="service_veh_tenant__5be953_idx",
                    ),
                    models.Index(
                        fields=["registration_no"],
                        name="service_veh_registr_5c6dfd_idx",
                    ),
                    models.Index(
                        fields=["vehicle_type"], name="service_veh_vehicle_b9d653_idx"
                    ),
                    models.Index(
                        fields=["fuel_type"], name="service_veh_fuel_ty_8414f5_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="servicevehicle",
            constraint=models.UniqueConstraint(
                fields=("tenant", "registration_no"), name="uniq_vehicle_reg_per_tenant"
            ),
        ),
    ]
