# Generated by Django 4.2.29 on 2026-03-27 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_and_map_fuel_types(apps, schema_editor):
    FuelType = apps.get_model("vehicles", "FuelType")
    ServiceVehicle = apps.get_model("vehicles", "ServiceVehicle")

    mapping = {
        "petrol": "Petrol",
        "diesel": "Diesel",
        "ev": "EV",
        "cng": "CNG",
        "hybrid": "Hybrid",
        "lpg": "LPG",
        "electric_hybrid": "Electric-Hybrid",
        "other": "Other",
    }

    fuel_types = {}
    for code, name in mapping.items():
        obj, _ = FuelType.objects.get_or_create(code=code.upper(), defaults={"name": name, "is_active": True})
        fuel_types[code] = obj

    for vehicle in ServiceVehicle.objects.all().only("id", "fuel_type"):
        old_code = (vehicle.fuel_type or "").strip().lower()
        fuel_type_obj = fuel_types.get(old_code) or fuel_types["other"]
        ServiceVehicle.objects.filter(pk=vehicle.pk).update(fuel_type_fk_id=fuel_type_obj.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "fuel_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="servicevehicle",
            name="fuel_type_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="vehicles.fueltype",
            ),
        ),
        migrations.RunPython(seed_and_map_fuel_types, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="servicevehicle",
            name="service_veh_fuel_ty_8414f5_idx",
        ),
        migrations.RemoveField(
            model_name="servicevehicle",
            name="fuel_type",
        ),
        migrations.RenameField(
            model_name="servicevehicle",
            old_name="fuel_type_fk",
            new_name="fuel_type",
        ),
        migrations.AlterField(
            model_name="servicevehicle",
            name="fuel_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_vehicles",
                to="vehicles.fueltype",
            ),
        ),
        migrations.AddIndex(
            model_name="servicevehicle",
            index=models.Index(fields=["fuel_type"], name="service_veh_fuel_ty_97e38c_idx"),
        ),
    ]
