# Generated by Django 4.2.29 on 2026-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_servicevehicle_brand_model_fk"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehiclebrand",
            name="uniq_vehicle_brand_code_per_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="vehiclebrand",
            name="uniq_vehicle_brand_name_per_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="vehiclemodel",
            name="uniq_vehicle_model_code_per_brand_tenant",
        ),
        migrations.AddField(
            model_name="vehiclebrand",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclebrand",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="vehiclebrand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("tenant", "code"),
                name="uniq_vehicle_brand_code_per_tenant_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclebrand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("tenant", "name"),
                name="uniq_vehicle_brand_name_per_tenant_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("tenant", "brand", "code"),
                name="uniq_vehicle_model_code_per_brand_tenant_active",
            ),
        ),
    ]
