# Generated by Django 4.2.29 on 2026-03-30 05:43

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_brand_model_soft_archive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehiclebrand",
            name="uniq_vehicle_brand_code_per_tenant_active",
        ),
        migrations.RemoveConstraint(
            model_name="vehiclebrand",
            name="uniq_vehicle_brand_name_per_tenant_active",
        ),
        migrations.RemoveConstraint(
            model_name="vehiclemodel",
            name="uniq_vehicle_model_code_per_brand_tenant_active",
        ),
        migrations.RemoveField(
            model_name="vehiclebrand",
            name="code",
        ),
        migrations.RemoveField(
            model_name="vehiclemodel",
            name="code",
        ),
        migrations.AddConstraint(
            model_name="vehiclebrand",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                condition=models.Q(("is_archived", False)),
                name="uniq_vehicle_brand_name_per_tenant_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemodel",
            constraint=models.UniqueConstraint(
                models.F("brand"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("is_archived", False)),
                name="uniq_vehicle_model_name_per_brand_active",
            ),
        ),
    ]
