# Generated by Django 5.2.12 on 2026-03-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_remove_brand_model_code"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="servicevehicle",
            new_name="service_veh_tenant__da35ce_idx",
            old_name="service_veh_tenant__brand_idx",
        ),
        migrations.RenameIndex(
            model_name="servicevehicle",
            new_name="service_veh_tenant__85d7ca_idx",
            old_name="service_veh_tenant__vmodel_idx",
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicle_models",
                to="vehicles.vehicletype",
            ),
        ),
    ]
