# Generated by Django 4.2.29 on 2026-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0008_add_vehicle_type_to_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicevehicle",
            name="photo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
