# Generated by Django 5.2.12 on 2026-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0009_add_photo_to_service_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicevehicle",
            name="engine_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
