# Generated by Django 5.2.12 on 2026-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0011_seed_body_type_vehicle_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclebrand",
            name="logo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
