# Generated by Django 5.2.12 on 2026-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_align_tenant_model_with_domain_branding_pii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="onboarded_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
