# Generated by Django 5.2.12 on 2026-03-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_onboarded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantbranding",
            name="dark_logo",
            field=models.CharField(
                blank=True,
                help_text="Relative path under MEDIA (LOCAL) or S3 object key.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantbranding",
            name="favicon",
            field=models.CharField(
                blank=True,
                help_text="Relative path under MEDIA (LOCAL) or S3 object key.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantbranding",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="Relative path under MEDIA (LOCAL) or S3 object key.",
                max_length=512,
                null=True,
            ),
        ),
    ]
