# Generated by Django 5.2.12 on 2026-08-02 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_branding_storage_charfields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantInvoiceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("account_number_encrypted", models.TextField(blank=True, null=True)),
                (
                    "account_number_key_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[("savings", "Savings"), ("current", "Current")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("ifsc_code", models.CharField(blank=True, default="", max_length=20)),
                ("bank_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "branch_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("upi_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        help_text="Relative path under MEDIA (LOCAL) or S3 object key.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_invoice_settings",
            },
        ),
    ]
