# Generated by Django 5.2.12 on 2026-08-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenantinvoicesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="advance_payment_percentage",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="currency_symbol",
            field=models.CharField(blank=True, default="₹", max_length=5),
        ),
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="estimate_charge_percentage",
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="replaced_parts_retention_days",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="service_warranty_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="tenantinvoicesettings",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Supports {{tenant_name}}, {{advance_payment_percentage}}, {{estimate_charge_percentage}}, {{replaced_parts_retention_days}}, {{service_warranty_days}}, {{currency_symbol}} placeholders — substituted with the values below when rendering the PDF.",
            ),
        ),
    ]
