# Generated by Django 5.2.12 on 2026-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenantinvoicesettings_advance_payment_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantpii",
            name="alternate_phone_encrypted",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantpii",
            name="alternate_phone_key_version",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
