# Generated by Django 5.2.12 on 2026-08-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenantpii_alternate_phone_encrypted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="show_terms_and_conditions",
            field=models.BooleanField(
                default=True,
                help_text="When off, the Terms & Conditions section is omitted from invoice PDFs regardless of the text above.",
            ),
        ),
    ]
