# Generated by Django 5.2.12 on 2026-08-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenantinvoicesettings_show_terms_and_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantinvoicesettings",
            name="show_gst_on_invoice",
            field=models.BooleanField(
                default=True,
                help_text="When off, GST rate/amount columns and the CGST/SGST tax breakdown are omitted from invoice PDFs — only the final total is shown. Does not affect job card PDFs, which always show GST.",
            ),
        ),
    ]
