# Generated by Django 5.2.12 on 2026-08-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenantinvoicesettings_show_gst_on_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantinvoicesettings",
            name="show_gst_on_invoice",
        ),
    ]
