# Generated by Django 5.2.12 on 2026-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_remove_tenantinvoicesettings_show_gst_on_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantbranding",
            name="business_hours",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-text display line, e.g. 'Mon - Sun · 9AM - 8PM'.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="instagram_handle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Without the @ — e.g. 'chezhiyancars'.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Digits with country code, e.g. '919840012345', for a wa.me link.",
                max_length=20,
            ),
        ),
    ]
