# Generated by Django 5.2.12 on 2026-04-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feature",
        ),
    ]
