# Generated by Django 4.2.29 on 2026-08-09 15:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0010_servicevehicle_engine_number"),
        ("tenants", "0007_tenantpii_alternate_phone_encrypted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_features",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_features",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryVehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("year", models.SmallIntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "mileage_km",
                    models.PositiveIntegerField(
                        default=0, help_text="Odometer reading in kilometers."
                    ),
                ),
                (
                    "listing_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_policy_no",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "registration_no",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("tax_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "photos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        default=list,
                        help_text="Storage keys (LOCAL path or S3 key) for uploaded listing photos, in display order.",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("sold", "Sold"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_vehicles",
                        to="vehicles.vehiclebrand",
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_vehicles",
                        to="vehicles.fueltype",
                    ),
                ),
                (
                    "key_features",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inventory_vehicles",
                        to="portfolio.inventoryfeature",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_vehicles",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_vehicles",
                        to="vehicles.vehiclemodel",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_vehicles",
                        to="vehicles.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_vehicles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="inventory_v_tenant__5b1103_idx",
                    ),
                    models.Index(
                        fields=["tenant", "brand"],
                        name="inventory_v_tenant__8cad18_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryfeature",
            index=models.Index(
                fields=["tenant", "name"], name="inventory_f_tenant__75d62e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryfeature",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                condition=models.Q(("is_archived", False)),
                name="uniq_inventory_feature_name_per_tenant_active",
            ),
        ),
    ]
