# Generated by Django 5.2.12 on 2026-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryvehicle",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("silver", "Silver"),
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("orange", "Orange"),
                    ("beige", "Beige"),
                    ("purple", "Purple"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
