# Generated by Django 5.2.12 on 2026-09-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_inventoryvehicle_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryfeature",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AddField(
            model_name="inventoryfeature",
            name="category",
            field=models.CharField(
                choices=[("safety", "Safety"), ("feature", "Feature")],
                default="feature",
                max_length=10,
            ),
        ),
    ]
