# Generated by Django 5.2.12 on 2026-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_inventoryfeature_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryvehicle",
            name="reasons_to_buy",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
