# Generated by Django 5.2.12 on 2026-09-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_inventoryvehicle_reasons_to_buy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryfeature",
            name="category",
            field=models.CharField(
                choices=[
                    ("comfort_convenience", "Comfort & Convenience"),
                    ("safety", "Safety"),
                    ("entertainment_communication", "Entertainment & Communication"),
                    ("exterior", "Exterior"),
                    ("interior", "Interior"),
                ],
                default="comfort_convenience",
                max_length=30,
            ),
        ),
    ]
