# Generated by Django 5.2.12 on 2026-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_remap_generic_feature_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryvehicle",
            name="offer_valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryvehicle",
            name="original_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
