# Generated by Django 5.2.12 on 2026-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_inventoryvehicle_offer_valid_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryvehicle",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
