# Generated by Django 5.2.12 on 2026-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_inventoryvehicle_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryvehicle",
            name="cover_thumbnail",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
