# Generated by Django 5.2.12 on 2026-03-20 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web_app", "Web Application"),
                            ("mobile_app", "Mobile Application"),
                            ("admin_panel", "Admin Panel"),
                            ("public_api", "Public API"),
                            ("contract", "Contract Document"),
                            ("cookie_banner", "Cookie Banner"),
                            ("kiosk", "Visitor Kiosk"),
                            ("import", "Data Import"),
                            ("system", "System Generated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "policy_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "consents",
            },
        ),
        migrations.CreateModel(
            name="ConsentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("retention_days", models.IntegerField(blank=True, null=True)),
                ("is_mandatory", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "consent_types",
            },
        ),
        migrations.CreateModel(
            name="ConsentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="consent.consent",
                    ),
                ),
            ],
            options={
                "db_table": "consent_history",
            },
        ),
        migrations.AddField(
            model_name="consent",
            name="consent_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="consent.consenttype",
            ),
        ),
        migrations.CreateModel(
            name="DataSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("platform_user", "Platform User"),
                            ("tenant_admin", "Tenant Admin"),
                            ("tenant_user", "Tenant User"),
                            ("client_employee", "Client Employee"),
                            ("visitor", "Visitor"),
                            ("opstrack_staff", "Opstrack Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_id", models.UUIDField()),
            ],
            options={
                "db_table": "data_subjects",
                "indexes": [
                    models.Index(
                        fields=["subject_type", "subject_id"],
                        name="data_subjec_subject_f8d3fc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_type", "subject_id"),
                        name="uq_data_subject_type_id",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="consent",
            name="data_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="consent.datasubject",
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["data_subject", "consent_type"],
                name="consents_data_su_ab6d01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(fields=["status"], name="consents_status_1ebc6d_idx"),
        ),
    ]
