# Generated by Django 5.2.12 on 2026-03-20 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_alter_tenant_onboarded_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="STARTER | PRO | PORTFOLIO | FULL_PLATFORM | ENTERPRISE",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("is_custom", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_users",
                    models.IntegerField(
                        default=0, help_text="Maximum number of users allowed."
                    ),
                ),
                (
                    "max_vehicles",
                    models.IntegerField(
                        default=0, help_text="Maximum number of vehicles allowed."
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "db_table": "plans",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_users",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum number of users allowed at the time of this history record.",
                    ),
                ),
                (
                    "max_vehicles",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum number of vehicles allowed at the time of this history record.",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for the subscription change",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_history",
                        to="billing.plan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_history",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT_STARTED", "Subscription Contract Started"),
                            ("CONTRACT_RENEWED", "Subscription Contract Renewed"),
                            ("CONTRACT_CANCELLED", "Subscription Contract Cancelled"),
                            ("ADDON_ADDED", "Add-on Added"),
                            ("ADDON_REMOVED", "Add-on Removed"),
                            ("LIMIT_OVERRIDDEN", "User Limit Overridden"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Snapshot of the change details"),
                ),
                (
                    "effective_at",
                    models.DateTimeField(help_text="When this change takes effect"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_ledger",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_ledger",
                "ordering": ["-effective_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_users",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum number of users allowed. Defaults to Plan's max_users but can be overridden.",
                    ),
                ),
                (
                    "max_vehicles",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum number of vehicles allowed. Defaults to Plan's max_vehicles but can be overridden.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=10,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        help_text="The ledger entry that created or last modified this subscription record",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resulting_subscriptions",
                        to="billing.subscriptionledger",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionAddOn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("USERS", "Extra Users"),
                            ("VEHICLES", "Extra Vehicles"),
                            ("STORAGE", "Extra Storage"),
                            ("LOCATIONS", "Extra Locations"),
                            ("FEATURES", "Premium Features"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "users_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of users added by this addon."
                    ),
                ),
                (
                    "vehicles_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of vehicles added by this addon."
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resulting_addons",
                        to="billing.subscriptionledger",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="billing.tenantsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_addons",
            },
        ),
        migrations.AddIndex(
            model_name="tenantsubscription",
            index=models.Index(
                fields=["tenant", "status"], name="tenant_subs_tenant__11bdb5_idx"
            ),
        ),
    ]
