# Generated by Django 5.2.12 on 2026-04-04 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobcards", "0003_shop_fees_and_line_detail"),
        ("tenants", "0004_tenant_branding_storage_charfields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(db_index=True, max_length=32)),
                ("fy_code", models.CharField(max_length=5)),
                ("sequence_no", models.PositiveIntegerField()),
                ("customer_name_encrypted", models.TextField(blank=True, null=True)),
                (
                    "customer_name_key_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("customer_phone_encrypted", models.TextField(blank=True, null=True)),
                (
                    "customer_phone_key_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("customer_email_encrypted", models.TextField(blank=True, null=True)),
                (
                    "customer_email_key_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("customer_address_encrypted", models.TextField(blank=True, null=True)),
                (
                    "customer_address_key_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "customer_gstin",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("is_pii_erased", models.BooleanField(default=False)),
                ("pii_erased_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tenant_gstin_snapshot",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("tenant_address_snapshot", models.TextField(blank=True, default="")),
                (
                    "vehicle_registration_no_snapshot",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "vehicle_label_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shop_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payment_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="jobcards.jobcard",
                    ),
                ),
                (
                    "payment_recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceFySequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fy_code", models.CharField(db_index=True, max_length=5)),
                ("last_seq", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_fy_sequences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_fy_sequences",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("description", models.CharField(max_length=500)),
                (
                    "detail_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "hsn_sac_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line_items",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "payment_status"], name="invoices_tenant__bbf1f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "fy_code"], name="invoices_tenant__b469d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "created_at"], name="invoices_tenant__e4fc29_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"),
                name="uniq_invoice_number_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicefysequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "fy_code"), name="uniq_invoice_fy_seq_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="invoicelineitem",
            index=models.Index(
                fields=["invoice", "sort_order"], name="invoice_lin_invoice_57646a_idx"
            ),
        ),
    ]
