# Generated by Django 4.2.29 on 2026-04-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="payment_mode",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="payment_recorded_at",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="payment_recorded_by",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="payment_reference",
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle_odometer_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle_vin_snapshot",
            field=models.CharField(blank=True, default="", max_length=17),
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_invoice_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoice_payments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "created_at"],
                        name="invoice_pay_invoice_35c5be_idx",
                    )
                ],
            },
        ),
    ]
