# Generated by Django 5.2.12 on 2026-04-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_pdf_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-created_at", "-invoice_number"]},
        ),
    ]
