# Generated by Django 5.2.12 on 2026-08-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_invoicelineitem_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="vehicle_brand_snapshot",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle_engine_no_snapshot",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle_model_snapshot",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle_year_snapshot",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
