# Generated by Django 5.2.12 on 2026-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_invoice_vehicle_brand_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="cgst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="sgst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
