# Generated by Django 5.2.12 on 2026-08-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_invoice_cancellation_reason_invoice_cancelled_at_and_more"),
        ("jobcards", "0009_jobcard_pdf_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="job_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="jobcards.jobcard",
            ),
        ),
    ]
