# Generated by Django 5.2.12 on 2026-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_alter_invoice_job_card"),
        ("tenants", "0010_remove_tenantinvoicesettings_show_gst_on_invoice"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoicefysequence",
            name="uniq_invoice_fy_seq_per_tenant",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("gst", "GST"), ("non_gst", "Non-GST")],
                db_index=True,
                default="gst",
                help_text="Decided once at generation time; immutable afterward.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoicefysequence",
            name="invoice_type",
            field=models.CharField(
                choices=[("gst", "GST"), ("non_gst", "Non-GST")],
                default="gst",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicefysequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "fy_code", "invoice_type"),
                name="uniq_invoice_fy_seq_per_tenant_type",
            ),
        ),
    ]
