# Generated by Django 5.2.12 on 2026-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0011_remove_invoicefysequence_uniq_invoice_fy_seq_per_tenant_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="round_off_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Adjustment applied to round total_amount to the nearest whole rupee (can be negative).",
                max_digits=12,
            ),
        ),
    ]
