# Generated by Django 5.2.12 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_invoice_round_off_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicelineitem",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive of GST"),
                    ("inclusive", "Inclusive of GST"),
                ],
                default="exclusive",
                help_text="Snapshot of the job card line's price_type at invoice generation time.",
                max_length=10,
            ),
        ),
    ]
