# Generated by Django 4.2.29 on 2026-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_move_state_city_to_masters"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="photo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
