# Generated by Django 5.2.12 on 2026-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_add_photo_to_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gstin",
            field=models.CharField(
                blank=True,
                help_text="Optional GSTIN for B2B customers (15-character GST identification number).",
                max_length=15,
                null=True,
            ),
        ),
    ]
