# Generated by Django 5.2.12 on 2026-09-06 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0005_customer_gstin"),
        ("services", "0004_serviceitem_service_type"),
        ("tenants", "0010_remove_tenantinvoicesettings_show_gst_on_invoice"),
        ("vehicles", "0011_seed_body_type_vehicle_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quotation_number", models.CharField(db_index=True, max_length=32)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("is_latest", models.BooleanField(default=True)),
                ("revision_reason", models.TextField(blank=True, null=True)),
                ("quotation_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("converted", "Converted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "round_off_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("terms_and_conditions", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_key", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="customers.customer",
                    ),
                ),
                (
                    "parent_quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="vehicles.servicevehicle",
                    ),
                ),
            ],
            options={
                "db_table": "quotations",
            },
        ),
        migrations.CreateModel(
            name="QuotationFySequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fy_code", models.CharField(db_index=True, max_length=5)),
                ("last_seq", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_fy_sequences",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_fy_sequences",
            },
        ),
        migrations.CreateModel(
            name="QuotationLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("part", "Part"), ("labour", "Labour")],
                        default="labour",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "detail_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "service_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_lines",
                        to="services.serviceitem",
                    ),
                ),
            ],
            options={
                "db_table": "quotation_line_items",
            },
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "quotation_number", "version"),
                name="uniq_quotation_number_version_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("tenant", "quotation_number"),
                name="uniq_latest_quotation_per_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gte", models.F("quotation_date")),
                    _connector="OR",
                ),
                name="quotation_valid_until_after_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal__gte", 0),
                    ("discount_amount__gte", 0),
                    ("taxable_amount__gte", 0),
                    ("cgst_amount__gte", 0),
                    ("sgst_amount__gte", 0),
                    ("igst_amount__gte", 0),
                    ("total_amount__gte", 0),
                ),
                name="quotation_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationfysequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "fy_code"), name="uniq_quotation_fy_seq_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="quotation_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="quotation_line_unit_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="quotation_line_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationlineitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("gst_percentage__gte", 0)),
                name="quotation_line_gst_percentage_non_negative",
            ),
        ),
    ]
