# Generated by Django 5.2.12 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationlineitem",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive of GST"),
                    ("inclusive", "Inclusive of GST"),
                ],
                default="exclusive",
                help_text="Snapshot of the linked catalog service item's price_type at sync time.",
                max_length=10,
            ),
        ),
    ]
